# Generated by Django 5.2.2 on 2025-06-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("db_main", "0002_default_site")]

    operations = [
        migrations.AlterModelOptions(name="user", options={}),
        migrations.AlterModelTable(name="auth0user", table="crowd_auth0_user"),
        migrations.AlterModelTable(name="user", table="crowd_user"),
    ]
